function [fitresult, gof] = createFit(Xaxis, b)
%CREATEFIT(XAXIS,B)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Xaxis
%      Y Output: b
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Apr-2017 11:59:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Xaxis, b );

% Set up fittype and options.
ft = fittype( 'a1*exp(-((x-b1)/(2*c1))^2) + a2*exp(-((x-b2)/(2*c2))^2) + a3*exp(-((x-b3)/(2*c3))^2) + a4*exp(-((x-b4)/(2*c4))^2) +off', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 210 390 540 680 0 0 0 0 0];
opts.StartPoint = [600 1981 1128 684 245 416 563 702 33 41 36 35 405]; %0tesla
%opts.StartPoint = [582 2034 1430 720 232 406 560 699 33 41 35 35 405]; %%5Tesla
opts.Upper = [Inf Inf Inf Inf 250 420 580 715 Inf Inf Inf Inf Inf];
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% % figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'b vs. Xaxis', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
% xlabel Xaxis
% ylabel b
% grid on


