function [fitresult, gof] = my2gaussfit(larray, yy)
%CREATEFIT(LARRAY,YY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : larray
%      Y Output: yy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Feb-2017 17:25:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( larray, yy );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 695 0 0 708 0];
opts.Upper = [Inf 705 500 Inf 720 500];
opts.StartPoint = [15000 703 10 15000 715 10];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



